### PR TITLE
Add JUNO-CREW

### PR DESCRIPTION
**Pull request by crazysoldier**

### CODE REVIEW

**Comment by crazysoldier** [comment]
all fixed

**Comment by zlounes** [comment]
Please do not use this pools created with JunoMint DEX Tools anymore. Please see the article on Medium for more details https://bit.ly/3sNSaNp

**Comment by zlounes** [comment]
@dimiandre or @crazysoldier you can close this PR.

**Comment by crazysoldier** [comment]
somehow its not possible to create a new pull, could you just add those correct lines ? 

{
      "id": "crew",
      "pool_id": "JUNO-CREW",
      "chain_id": "juno-1",
      "token_address": "juno18cpnn3cnrr9xq7r0cqp7shl7slasf27nrmskw4rrw8c6hyp8u7rqe2nulg",
      "swap_address": "juno1zpv53vs79que4x6ks5v5q26pt44j7ehrcfc5zxxnhautklzv76mspmj0yg",
      "symbol": "CREW",
      "name": "CryptoCrew",
      "decimals": "3",
      "logoURI": "https://ipfs.io/ipfs/QmaAuJ8HHwsh9R2RduFQEbz3VLdQxHK7KWg4F3GbJA4KNf",
      "tags": [
        "cw20"
      ],
      "native": false,
      "denom": "crew"
    }

**Comment by crazysoldier** [comment]
now pls add this finally : https://github.com/CosmosContracts/junoswap-asset-list/pull/30

**Pull request closed without merging**
