### PR TITLE
Add JUNO-NGM

### PR DESCRIPTION
**Pull request by Golden-Ratio-Staking**

### CODE REVIEW

**Comment by dimiandre** [comment]
What is boson?

please use only logos from github

**Comment by Golden-Ratio-Staking** [comment]
> What is boson?
> 
> please use only logos from github

I am not adding BOSON. I am only adding NGM and EEUR. Both are using github logos. Please advise.

**Comment by Golden-Ratio-Staking** [comment]
I'm seeing BOSON was on asset list when I tried PR 17 days ago. Will edit

**Comment by Golden-Ratio-Staking** [comment]
Removal of BOSON complete.

**Comment by Golden-Ratio-Staking** [comment]
Any update on this? @dimiandre

**Review by joeabbey — APPROVED** [review]
LGTM

**Pull request merged**
